<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            /*
            Elements\Handler\ElementsReadHandler::class => Elements\Handler\ElementsReadHandlerFactory::class,
            Projects\Handler\ProjectsAuthHandler::class => Projects\Handler\ProjectsAuthHandlerFactory::class,
            Projects\Handler\ProjectsCreateHandler::class => Projects\Handler\ProjectsCreateHandlerFactory::class,
            Projects\Handler\ProjectsReadHandler::class => Projects\Handler\ProjectsReadHandlerFactory::class,
            Projects\Handler\ProjectsWriteHandler::class => Projects\Handler\ProjectsWriteHandlerFactory::class,
            */
        ],
    ],
];
